- name: Check if Nginx is installed
  command: command -v nginx
  register: nginx_check
  failed_when: false
  changed_when: false

- name: Install Nginx if not installed
  apt:
    name: nginx
    state: present
    update_cache: yes
  when: nginx_check.rc != 0

- name: Ensure Nginx service is running and enabled
  service:
    name: nginx
    state: started
    enabled: yes
