---
- name: Cập nhật danh sách package
  apt:
    update_cache: yes

- name: Cài đặt Nginx, PHP-FPM, PHP-MySQL và MySQL Server
  apt:
    name:
      - nginx
      - php-fpm
      - php-mysql
      - mysql-server  # Cài đặt MySQL Server
    state: present

- name: Cài đặt pip3
  apt:
    name: python3-pip
    state: present

- name: Cài đặt PyMySQL (cho Python 3)
  pip:
    name: PyMySQL
    state: present

- import_tasks: detect_php.yml

- name: Đảm bảo Nginx đang chạy
  service:
    name: nginx
    state: started
    enabled: yes

# - name: Đảm bảo PHP-FPM đang chạy
#   service:
#     name: "{{ php_fpm_service }}"
#     state: started
#     enabled: yes

- name: Kiểm tra config PHP-FPM
  command: php-fpm8.1 -t
  register: php_fpm_check
  failed_when: "'error' in php_fpm_check.stderr"

- name: Bật dịch vụ PHP-FPM
  service:
    name: php8.1-fpm
    state: started
    enabled: yes
  when: php_fpm_check.rc == 0

- name: Đảm bảo dịch vụ MySQL đang chạy
  systemd:
    name: mysql
    state: started
    enabled: yes