- name: Copy script cấu hình PHP vào Desktop
  win_copy:
    src: files/configure_php_iis.ps1
    dest: C:\Users\Administrator\Desktop\configure_php_iis.ps1

- name: Thực thi script cấu hình PHP
  win_shell: "powershell.exe -ExecutionPolicy Bypass -File C:\\Users\\Administrator\\Desktop\\configure_php_iis.ps1"

- name: Tạo Application Pool cho PHP
  ansible.windows.win_shell: |
    New-WebAppPool -Name "AnsibleWebPool"
    Set-ItemProperty IIS:\AppPools\AnsibleWebPool -Name managedRuntimeVersion -Value ""
    Set-ItemProperty IIS:\AppPools\AnsibleWebPool -Name enable32BitAppOnWin64 -Value True
    Set-ItemProperty IIS:\AppPools\AnsibleWebPool -Name processModel.identityType -Value "ApplicationPoolIdentity"
    
- name: Cấu hình website trong IIS
  community.windows.win_iis_website:
    name: "{{ iis_site_name }}"
    state: started
    physical_path: "{{ web_root }}"
    port: "{{ iis_port }}"
    hostname: "{{ iis_hostname }}"
    ip: "{{ iis_ip }}"
    application_pool: AnsibleWebPool  # Đồng bộ với tên Application Pool ở trên

- name: Xóa tất cả binding hiện có của site "{{ iis_site_name }}"
  community.windows.win_iis_webbinding:
    name: "{{ iis_site_name }}"
    state: absent
  register: binding_cleanup
  ignore_errors: true

- name: Thêm IIS binding mới (*:{{ iis_port }}:)
  community.windows.win_iis_webbinding:
    name: "{{ iis_site_name }}"
    protocol: http
    port: "{{ iis_port }}"
    ip: "*"
    state: present
