- name: Gỡ bỏ IIS bằng DISM (nếu bị lỗi)
  win_shell: |
    DISM /Online /Disable-Feature /FeatureName:IIS-WebServer /NoRestart
  ignore_errors: true

- name: Cài đặt IIS và các tính năng cần thiết bằng DISM
  win_shell: |
    DISM /Online /Enable-Feature /FeatureName:IIS-WebServer /All /NoRestart
    DISM /Online /Enable-Feature /FeatureName:IIS-WebServerRole /All /NoRestart
    DISM /Online /Enable-Feature /FeatureName:IIS-ISAPIExtensions /All /NoRestart
    DISM /Online /Enable-Feature /FeatureName:IIS-ISAPIFilter /All /NoRestart
    DISM /Online /Enable-Feature /FeatureName:IIS-ASP /All /NoRestart
    DISM /Online /Enable-Feature /FeatureName:IIS-ASPNET45 /All /NoRestart
    DISM /Online /Enable-Feature /FeatureName:IIS-HttpLogging /All /NoRestart
    DISM /Online /Enable-Feature /FeatureName:IIS-RequestMonitor /All /NoRestart
    DISM /Online /Enable-Feature /FeatureName:IIS-HttpTracing /All /NoRestart
    DISM /Online /Enable-Feature /FeatureName:IIS-Security /All /NoRestart
    DISM /Online /Enable-Feature /FeatureName:IIS-Filtering /All /NoRestart
    DISM /Online /Enable-Feature /FeatureName:IIS-StaticContent /All /NoRestart
    DISM /Online /Enable-Feature /FeatureName:IIS-DefaultDocument /All /NoRestart
    DISM /Online /Enable-Feature /FeatureName:IIS-DirectoryBrowsing /All /NoRestart
    DISM /Online /Enable-Feature /FeatureName:IIS-HttpErrors /All /NoRestart
    DISM /Online /Enable-Feature /FeatureName:IIS-HttpRedirect /All /NoRestart
    DISM /Online /Enable-Feature /FeatureName:IIS-NetFxExtensibility45 /All /NoRestart
    DISM /Online /Enable-Feature /FeatureName:IIS-ApplicationDevelopment /All /NoRestart
    DISM /Online /Enable-Feature /FeatureName:IIS-ManagementTools /All /NoRestart
    DISM /Online /Enable-Feature /FeatureName:IIS-ManagementConsole /All /NoRestart
  register: dism_install

- name: Khởi động lại nếu cần thiết
  win_reboot:
  when: dism_install.stdout is search("restart required")

- name: Đảm bảo IIS đang chạy sau khi cài đặt
  win_service:
    name: "{{ item }}"
    state: started
  loop:
    - W3SVC
    - WAS
