---
- name: Cấu hình quyền truy cập cho IIS_IUSRS
  win_acl:
    path: "{{ web_root }}"
    user: "{{ iis_user }}"
    rights: FullControl
    type: allow
    state: present

- name: Cấu hình website trong IIS với thư mục chính xác
  win_iis_website:
    name: "{{ iis_site_name }}"
    state: started
    physical_path: "{{ web_root }}\\ansible-web-main"  # Trỏ đúng vào thư mục chứa mã nguồn
    port: "{{ iis_port }}"
    hostname: "{{ iis_hostname }}"
    ip: "{{ iis_ip }}"


- name: Copy script cấu hình PHP vào Windows
  ansible.builtin.copy:
    src: files/configure_php_iis.ps1
    dest: C:\temp\configure_php_iis.ps1

- name: Thực thi script cấu hình PHP
  ansible.windows.win_shell: |
    powershell.exe -ExecutionPolicy Bypass -File C:\temp\configure_php_iis.ps1
