---
### KIỂM TRA VÀ CÀI ĐẶT CHOCOLATEY ###
- name: Kiểm tra Chocolatey đã cài đặt chưa
  win_stat:
    path: C:\ProgramData\chocolatey\bin\choco.exe
  register: choco_status

- name: Cài đặt Chocolatey nếu chưa có
  win_shell: |
    Set-ExecutionPolicy Bypass -Scope Process -Force; 
    [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; 
    iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
  when: not choco_status.stat.exists

### KIỂM TRA VÀ CÀI ĐẶT MYSQL & PHP ###
- name: Lấy danh sách phần mềm cài đặt qua Chocolatey
  win_shell: choco list
  register: choco_list

- name: Kiểm tra MySQL và PHP đã có trong Chocolatey chưa
  set_fact:
    mysql_installed: "{{ 'mysql' in choco_list.stdout }}"
    php_installed: "{{ 'php' in choco_list.stdout }}"

- name: Cài đặt MySQL và PHP nếu chưa có
  win_chocolatey:
    name: "{{ item.name }}"
    version: "{{ item.version | default(omit) }}"
    state: present
  loop:
    - { name: "mysql", version: "8.4.4" }
    - { name: "php" }
  when: "not (item.name + '_installed') | bool"

### LẤY ĐƯỜNG DẪN MYSQL & PHP ###
- name: Lấy đường dẫn chính xác của MySQL và PHP
  win_shell: |
    (Get-Command {{ item }}).Source
  register: bin_paths
  loop:
    - mysql
    - php
  when: "{{ item }}_installed"

- name: Đặt biến đường dẫn MySQL và PHP
  set_fact:
    mysql_bin: "{{ bin_paths.results[0].stdout | trim }}"
    php_bin: "{{ bin_paths.results[1].stdout | trim }}"

### CÀI ĐẶT IIS VÀ CẤU HÌNH ###
- name: Lấy danh sách tính năng IIS đã cài đặt
  win_shell: Dism /online /Get-Features | findstr /C:"IIS-"
  register: iis_features

- name: Cài đặt IIS nếu chưa có
  win_shell: Dism /online /Enable-Feature /FeatureName:{{ item }} /All
  loop:
    - IIS-WebServerRole
    - IIS-WebServer
    - IIS-ApplicationDevelopment
    - IIS-CGI
    - IIS-ISAPIExtensions
    - IIS-ISAPIFilter
    - IIS-CommonHttpFeatures
    - IIS-Security
    - IIS-RequestFiltering
  when: "item not in iis_features.stdout"

- name: Đảm bảo IIS đang chạy
  win_service:
    name: W3SVC
    state: started

### XÓA CẤU HÌNH CŨ ###
- name: Kiểm tra và xóa thư mục web_root nếu tồn tại
  win_file:
    path: "{{ web_root }}"
    state: absent

- name: Xóa website trong IIS nếu tồn tại
  win_iis_website:
    name: "{{ iis_site_name }}"
    state: absent
  ignore_errors: true

### TRIỂN KHAI MÃ NGUỒN ###
- name: Tạo thư mục web_root
  win_file:
    path: "{{ web_root }}"
    state: directory

- name: Tải và giải nén source code
  win_get_url:
    url: "{{ repo_url }}"
    dest: "{{ zip_dest }}"

- name: Giải nén source code
  win_unzip:
    src: "{{ zip_dest }}"
    dest: "{{ web_root }}"
    remote_src: yes

- name: Cấu hình website trong IIS
  win_iis_website:
    name: "{{ iis_site_name }}"
    state: started
    physical_path: "{{ web_root }}\\ansible-web-main"
    port: "{{ iis_port }}"
    hostname: "{{ iis_hostname }}"
    ip: "{{ iis_ip }}"

### CẤU HÌNH MYSQL ###
- name: Kiểm tra MySQL đã cài đặt hay chưa
  win_shell: "{{ mysql_bin }} --version"
  register: mysql_version
  ignore_errors: true

- name: Import database nếu MySQL hoạt động
  win_command: >
    "{{ mysql_bin }}" -u root -ppassword --execute="source {{ web_root }}\\ansible-web-main\\test_db.sql"
  register: db_import
  when: mysql_version.rc == 0
  ignore_errors: true


- name: Kiểm tra kết quả import database
  ansible.builtin.debug:
    msg: >
      {% if db_import is defined and db_import.rc == 0 %}
        Import database thành công!
      {% elif db_import is defined %}
        Lỗi import database: {{ db_import.msg }}
      {% else %}
        Task import database đã bị bỏ qua.
      {% endif %}


### CẤU HÌNH PHP ###
- name: Đảm bảo thư mục PHP tồn tại
  win_file:
    path: C:\php
    state: directory

- name: Copy file php.ini
  win_copy:
    src: files/php.ini
    dest: C:\php\php.ini

- name: Cấu hình biến môi trường PHPRC
  win_shell: "[System.Environment]::SetEnvironmentVariable('PHPRC', 'C:\\php', 'Machine')"
  args:
    executable: powershell

- name: Thực thi script cấu hình PHP
  win_shell: "powershell.exe -ExecutionPolicy Bypass -File C:\\Users\\Administrator\\Desktop\\configure_php_iis.ps1"

### KIỂM TRA LẠI MYSQL ###
- name: Kiểm tra lại MySQL
  win_shell: "{{ mysql_bin }} --version"
  register: mysql_version
  ignore_errors: true

- name: Hiển thị phiên bản MySQL
  debug:
    msg: "{{ mysql_version.stdout }}"
  when: mysql_version.rc == 0
